version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
